# --- HTTP -> HTTPS ---
server {
    listen 80;
    listen [::]:80;
    server_name pesquisa.yokoapps.com.br;
    return 301 https://$host$request_uri;
}

# --- Servidor HTTPS: Pesquisa ---
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name pesquisa.yokoapps.com.br;

    ssl_certificate /etc/letsencrypt/live/yokoapps.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yokoapps.com.br/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 50M;
    access_log /var/log/nginx/pesquisa_access.log;
    error_log /var/log/nginx/pesquisa_error.log;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # Normaliza caso acessem pesquisa.yokoapps.com.br/pesquisa/...
    location ~ ^/pesquisa/?(.*)$ {
        return 301 https://pesquisa.yokoapps.com.br/$1$is_args$args;
    }

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:8888;
    }
}
