# Enviar solicitação de avaliação para avaliadores

name: Solicitar avaliação para avaliadores

on: 
  workflow_dispatch:
  schedule:
    - cron: '45 10 * * 2,4' # Executa 2 vezes na semana as 10:45 (UTC)
  
permissions:
  contents: read

jobs:
  avaliacao:
    runs-on: ubuntu-latest
    steps:
      - name: enviando comandos ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /backup/pesquisa3
            export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}
            ./cron.avaliacao.sh
            history -c && history -w
            cat /dev/null > ~/.bash_history