# This workflow will BACKUP the system when a cron is available.

name: Backup do BD

on: 
  workflow_dispatch:
  schedule:
    - cron: '45 3 * * *' # Executa diariamente as 03:45 (UTC)
  
permissions:
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: enviando comandos ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.YOKO_HOST }}
          username: ${{ secrets.YOKO_USERNAME }}
          key: ${{ secrets.YOKO_KEY }}
          port: ${{ secrets.YOKO_PORT }}
          script: |
            cd /backup/pesquisa3
            export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}
            ./backup.mysql.sh
            history -c && history -w
            cat /dev/null > ~/.bash_history