# Enviar solicitação de frequencia para os orientadores

name: Solicitar envio de frequencia dos bolsistas

on: 
  workflow_dispatch:
  schedule:
    - cron: '59 10 5-30/5 * *' # Executa a cada 5 dias entre os dias 5-30 as 10:59 (UTC)
  
permissions:
  contents: read

jobs:
  frequencia:
    runs-on: ubuntu-latest
    steps:
      - name: enviando comandos ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /backup/pesquisa3
            export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}
            ./cron.frequencia.sh
            history -c && history -w
            cat /dev/null > ~/.bash_history